services:
  db:
    image: postgres:latest
    container_name: Logiqo_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    restart: unless-stopped
