services:
  postgres:
    image: postgres:latest
    container_name: Logiqo_db
    environment:
      - POSTGRES_DB=logiqo
      - POSTGRES_USER=logiqo
      - POSTGRES_PASSWORD=logiqo
    ports:
      - '5432:5432'
    restart: unless-stopped
